### ISSUE TITLE
garden task compiles whole project

### ISSUE THREAD

**Issue by devurandom** [noprompt/lein-garden#19]
Running `lein garden auto main` with my project.clj also compiles the whole project's cljsbuild rules.

It would be nice if garden could automatically find out which files need to be compiled to be able to compile the style file, and then just build that together with the style file in an own compilation step, instead of building all cljsbuild rules just in case.

An alternative would be to allow the user to specify which files are necessary to build the style.

I am using lein-garden-0.1.9.

**Comment by noprompt** [comment]
I'm closing this issue for now. I'm happy to reopen it when there's a solution.
