### ISSUE TITLE
lein-garden 2.6 exists, but doesn't seem official?

### ISSUE THREAD

**Issue by zentrope** [noprompt/lein-garden#33]
`lein-garden` 2.6 exists on Clojars:

https://clojars.org/lein-garden/versions/0.2.6

yet the `project.clj` file is still 2.6-SNAPSHOT. I pulled down the jar and noticed it didn't have any recent changes in there.

Some sort of accidental deploy?

**Comment by noprompt** [comment]
No. Some commits had not been pushed on my end.
